swagger: '2.0'
info:
  title: Popcash API
  version: 1.0.0
host: api.popcash.net
schemes:
  - http
  - https
basePath: /v1
produces:
  - application/json
parameters:
  api_key:
    name: api_key
    in: query
    required: true
    type: string
    description: Your api key
paths:
  /account:
    get:
      summary: Account information
      description: |
        Get information about current acount
      parameters:
        - $ref: '#/parameters/api_key'
      tags:
        - Account
      responses:
        '200':
          description: Account information
          schema:
            $ref: '#/definitions/Account'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /campaigns:
    get:
      summary: List all campaigns
      description: |
        List all campaigns for the current user.
      parameters:
        - $ref: '#/parameters/api_key'
        - name: status
          in: query
          description: Filter campaigns by status
          required: false
          type: string
          enum:
            - pending
            - running
            - out of funds
            - paused
            - banned
            - rejected
      tags:
        - Campaigns
      responses:
        '200':
          description: An array of campaigns
          schema:
            type: array
            items:
              $ref: '#/definitions/CampaignSummary'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/campaigns/{id}':
    get:
      summary: Get campaign details.
      description: |
        Get all the deils about a campaign by id.
      parameters:
        - $ref: '#/parameters/api_key'
        - name: id
          in: path
          description: Campaign id
          required: true
          type: number
      tags:
        - Campaigns
      responses:
        '200':
          description: An array of campaigns
          schema:
            type: array
            items:
              $ref: '#/definitions/Campaign'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/campaigns/{id}/start':
    post:
      summary: Starts a campaign.
      parameters:
        - $ref: '#/parameters/api_key'
        - name: id
          in: path
          description: Campaign id
          required: true
          type: number
      tags:
        - Campaigns
      responses:
        '200':
          description: Campaign response
          schema:
            $ref: '#/definitions/StartStopResponse'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/campaigns/{id}/pause':
    post:
      summary: Pause a campaign.
      parameters:
        - $ref: '#/parameters/api_key'
        - name: id
          in: path
          description: Campaign id
          required: true
          type: number
      tags:
        - Campaigns
      responses:
        '200':
          description: Campaign response
          schema:
            $ref: '#/definitions/StartStopResponse'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/campaigns/{id}/targeting':
    post:
      summary: Change targeting for a campaign.
      description: >
        Targeting can be including r excluding. You must provide the type of
        targeting, sites id and wheter

        this rules will be appended to existing ones (default behaviour) or will
        replace the existing ones.
      parameters:
        - $ref: '#/parameters/api_key'
        - name: id
          in: path
          description: Campaign id
          required: true
          type: number
        - name: targeting
          in: body
          description: Targeting object
          required: true
          schema:
            $ref: '#/definitions/Targeting'
      consumes:
        - application/json
      tags:
        - Campaigns
      responses:
        '200':
          description: Campaign response
          schema:
            $ref: '#/definitions/MessageResponse'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/campaigns/{id}/adjust-budget':
    post:
      summary: Adjust budget for a campaign.
      description: >
        You can add or withdraw money to a campaign buget. If you want to add
        money adjust with a positive amount

        If you want to withdraw adjust it with a negative amount.
      parameters:
        - $ref: '#/parameters/api_key'
        - name: id
          in: path
          description: Campaign id
          required: true
          type: number
        - name: budget
          in: body
          description: Adjust budget object
          required: true
          schema:
            $ref: '#/definitions/AdjustBudget'
      consumes:
        - application/json
      tags:
        - Campaigns
      responses:
        '200':
          description: Campaign response
          schema:
            $ref: '#/definitions/MessageResponse'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/campaigns/{id}/reports/{groupBy}/{startDate}/{endDate}':
    get:
      summary: Create report for a campaign.
      description: >
        You can create reports for a campaign.
      parameters:
        - $ref: '#/parameters/api_key'
        - name: id
          in: path
          description: Campaign id
          required: true
          type: number
        - name: groupBy
          in: path
          description: Group by clause
          required: true
          type: string
          enum:
            - day
            - country
            - source
        - name: startDate
          in: path
          description: Start date in ISO 8601 format (example 2015-11-12)
          required: true
          type: string
        - name: endDate
          in: path
          description: End date in ISO 8601 format (example 2015-11-12)
          required: true
          type: string
      tags:
        - Campaigns
      responses:
        '200':
          description: Report Id
          schema:
            $ref: '#/definitions/CreateReportResponse'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/campaigns/{campaignId}/reports/{reportId}':
    get:
      summary: Get report by id
      description: >
        When the report is ready you can retrieve it. It is stored for 24 hours
      parameters:
        - $ref: '#/parameters/api_key'
        - name: campaignId
          in: path
          description: Campaign id
          required: true
          type: string
        - name: reportId
          in: path
          description: Report Id
          required: true
          type: string
      responses:
        '200':
          description: Report text
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Account:
    type: object
    properties:
      uid:
        type: number
        description: User Id
      username:
        type: string
        description: Username
      email:
        type: string
        description: User email
      name:
        type: string
        description: Display user name
      balance:
        type: number
        description: Account balance
      campaignsCount:
        type: number
        description: The number of campaigns
      campaigns:
        type: object
        properties:
          'pending':
            type: array
            items:
              $ref: '#/definitions/CampaignSummary'
              description: Out of funds campaigns
          'running':
            type: array
            items:
              $ref: '#/definitions/CampaignSummary'
              description: Out of funds campaigns
          'out of funds':
            type: array
            items:
              $ref: '#/definitions/CampaignSummary'
              description: Out of funds campaigns
          'paused':
            type: array
            items:
              $ref: '#/definitions/CampaignSummary'
              description: Out of funds campaigns
          'banned':
            type: array
            items:
              $ref: '#/definitions/CampaignSummary'
              description: Out of funds campaigns
          'rejected':
            type: array
            items:
              $ref: '#/definitions/CampaignSummary'
              description: Out of funds campaigns
  CampaignSummary:
    type: object
    properties:
      campaignId:
        type: number
        description: Unique identifier for campaign.
      name:
        type: string
        description: Campaign name.
      url:
        type: string
        description: Campaign URL.
      totalBudget:
        type: number
        description: Total budget for this campaign.
      remainingBudget:
        type: number
        description: Remaining budget for this campaign.
      bid:
        type: number
        description: Current bid for campaign.
      status:
        type: string
        description: Current status of campaign.
  Campaign:
    type: object
    properties:
      campaignId:
        type: number
        description: Unique identifier for campaign.
      name:
        type: string
        description: Campaign name.
      url:
        type: string
        description: Campaign URL.
      totalBudget:
        type: number
        description: Total budget for this campaign.
      remainingBudget:
        type: number
        description: Remaining budget for this campaign.
      bid:
        type: number
        description: Current bid for campaign.
      status:
        type: string
        description: Current status of campaign.
      included:
        type: array
        items:
          type: number
          description: Id of included sites
      excluded:
        type: array
        items:
          type: number
          description: Id of excluded sites
      countries:
        type: array
        items:
          type: string
          description: 2 digit country code (ISO 3166-2)
      operating_systems:
        type: array
        items:
          $ref: '#/definitions/SimpleObject'
          description: Target operating systems
      categories:
        type: array
        items:
          $ref: '#/definitions/SimpleObject'
          description: Target operating systems
      browsers:
        type: array
        items:
          $ref: '#/definitions/SimpleObject'
          description: Target operating systems
  SimpleObject:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  CampaignSummary:
    type: object
    properties:
      campaignId:
        type: string
      status:
        type: string
  StartStopResponse:
    type: object
    properties:
      campaignId:
        type: string
      message:
        type: string
  MessageResponse:
    type: object
    properties:
      message:
        type: string
  CreateReportResponse:
    type: object
    properties:
      reportId:
        type: string
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
        description: Status Code
      err:
        type: string
        description: Error unique identifier. Contact support asking for this error code.
  AdjustBudget:
    type: object
    properties:
      amount:
        type: number
        description: Amount of money (positive or negative) to be added or withdrawn to/from campaign budget
      start:
        type: string
        default: 'true'
        enum:
          - 'true'
          - 'false'
        description: Wheter to start or not the campaign after adjustement
  Targeting:
    type: object
    properties:
      targeting:
        type: string
        description: Status Code
        default: included
        enum:
          - included
          - excluded
      siteList:
        type: array
        items:
          type: number
        description: Ids for sites to be included or excluded
      mode:
        type: string
        default: replace
        enum:
          - append
          - replace
